### ISSUE TITLE
Incompatible version of terraform-null-label with TF 0.12.x

### ISSUE THREAD

**Issue by kuritonasu** [cloudposse/terraform-aws-iam-user#6]
When using either _master_ or the _terraform-0.12_ branches, Terraform v0.12.20 complains about the **terraform-null-label** module, as the present module references **terraform-null-label module.git?ref=0.11/master** :

>Error: Unsupported Terraform Core version
>
> Module username.label (from
> "git::https://github.com/cloudposse/terraform-null-label.git?ref=0.11/master")
> does not support Terraform version 0.12.20. To proceed, either choose another
> supported Terraform version or update the module's version constraint. Version
> constraints are normally set for good reason, so updating the constraint may
> lead to other errors or unexpected behavior.

**Comment by davidkarlsen** [comment]
Also breaks in 0.13:
```
Error: Module does not support for_each

  on main.tf line 20, in module "ecr":
  20:   for_each = var.repos

Module "ecr" cannot be used with for_each because it contains a nested
provider configuration for "null", at
.terraform/modules/ecr.iam_repo_user.label/provider.tf:1,10-16.

This module can be made compatible with for_each by changing it to receive all
of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
```
