### ISSUE TITLE
User Identity permissions

### ISSUE THREAD

**Issue by luis02lopez** [cloudposse/terraform-aws-iam-user#8]
Hello!

I'm wondering the reason why don't you have the possibility of adding policy documents to the user, as you can add them through the group or direct policy documents.

Ref.: [https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html) "You use policies to define the permissions for an identity (user, group, or role)"

**Comment by Gowiem** [comment]
@luis02lopez I believe this is because it's typically a bad practice. If you feel strongly about it, then I'm not necessarily apposed however. Feel free to put up a PR and we'll discuss it with the contributor team. If you do not need this anyone more then, please kindly close this issue out.

**Comment by Gowiem** [comment]
Closing out as no response 3 weeks later. Feel free to reopen and we can discuss!
